# CMAKE generated file: DO NOT EDIT!
# Generated by "MinGW Makefiles" Generator, CMake Version 3.29

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

SHELL = cmd.exe

# The CMake executable.
CMAKE_COMMAND = F:\LockD\CMP2025\Third_Year\Second_Term\Computer_Graphics\CMake\bin\cmake.exe

# The command to remove a file.
RM = F:\LockD\CMP2025\Third_Year\Second_Term\Computer_Graphics\CMake\bin\cmake.exe -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = E:\Summer2024\SiemensFinalProjectMilestone2

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = E:\Summer2024\SiemensFinalProjectMilestone2

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	F:\LockD\CMP2025\Third_Year\Second_Term\Computer_Graphics\CMake\bin\cmake-gui.exe -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	F:\LockD\CMP2025\Third_Year\Second_Term\Computer_Graphics\CMake\bin\cmake.exe --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start E:\Summer2024\SiemensFinalProjectMilestone2\CMakeFiles E:\Summer2024\SiemensFinalProjectMilestone2\\CMakeFiles\progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start E:\Summer2024\SiemensFinalProjectMilestone2\CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles\Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named ORANPacketsSimulator

# Build rule for target.
ORANPacketsSimulator: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 ORANPacketsSimulator
.PHONY : ORANPacketsSimulator

# fast build rule for target.
ORANPacketsSimulator/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\ORANPacketsSimulator.dir\build.make CMakeFiles/ORANPacketsSimulator.dir/build
.PHONY : ORANPacketsSimulator/fast

ECPRI.obj: ECPRI.cpp.obj
.PHONY : ECPRI.obj

# target to build an object file
ECPRI.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\ORANPacketsSimulator.dir\build.make CMakeFiles/ORANPacketsSimulator.dir/ECPRI.cpp.obj
.PHONY : ECPRI.cpp.obj

ECPRI.i: ECPRI.cpp.i
.PHONY : ECPRI.i

# target to preprocess a source file
ECPRI.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\ORANPacketsSimulator.dir\build.make CMakeFiles/ORANPacketsSimulator.dir/ECPRI.cpp.i
.PHONY : ECPRI.cpp.i

ECPRI.s: ECPRI.cpp.s
.PHONY : ECPRI.s

# target to generate assembly for a file
ECPRI.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\ORANPacketsSimulator.dir\build.make CMakeFiles/ORANPacketsSimulator.dir/ECPRI.cpp.s
.PHONY : ECPRI.cpp.s

ORAN.obj: ORAN.cpp.obj
.PHONY : ORAN.obj

# target to build an object file
ORAN.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\ORANPacketsSimulator.dir\build.make CMakeFiles/ORANPacketsSimulator.dir/ORAN.cpp.obj
.PHONY : ORAN.cpp.obj

ORAN.i: ORAN.cpp.i
.PHONY : ORAN.i

# target to preprocess a source file
ORAN.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\ORANPacketsSimulator.dir\build.make CMakeFiles/ORANPacketsSimulator.dir/ORAN.cpp.i
.PHONY : ORAN.cpp.i

ORAN.s: ORAN.cpp.s
.PHONY : ORAN.s

# target to generate assembly for a file
ORAN.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\ORANPacketsSimulator.dir\build.make CMakeFiles/ORANPacketsSimulator.dir/ORAN.cpp.s
.PHONY : ORAN.cpp.s

Packet.obj: Packet.cpp.obj
.PHONY : Packet.obj

# target to build an object file
Packet.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\ORANPacketsSimulator.dir\build.make CMakeFiles/ORANPacketsSimulator.dir/Packet.cpp.obj
.PHONY : Packet.cpp.obj

Packet.i: Packet.cpp.i
.PHONY : Packet.i

# target to preprocess a source file
Packet.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\ORANPacketsSimulator.dir\build.make CMakeFiles/ORANPacketsSimulator.dir/Packet.cpp.i
.PHONY : Packet.cpp.i

Packet.s: Packet.cpp.s
.PHONY : Packet.s

# target to generate assembly for a file
Packet.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\ORANPacketsSimulator.dir\build.make CMakeFiles/ORANPacketsSimulator.dir/Packet.cpp.s
.PHONY : Packet.cpp.s

Program.obj: Program.cpp.obj
.PHONY : Program.obj

# target to build an object file
Program.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\ORANPacketsSimulator.dir\build.make CMakeFiles/ORANPacketsSimulator.dir/Program.cpp.obj
.PHONY : Program.cpp.obj

Program.i: Program.cpp.i
.PHONY : Program.i

# target to preprocess a source file
Program.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\ORANPacketsSimulator.dir\build.make CMakeFiles/ORANPacketsSimulator.dir/Program.cpp.i
.PHONY : Program.cpp.i

Program.s: Program.cpp.s
.PHONY : Program.s

# target to generate assembly for a file
Program.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\ORANPacketsSimulator.dir\build.make CMakeFiles/ORANPacketsSimulator.dir/Program.cpp.s
.PHONY : Program.cpp.s

configurations.obj: configurations.cpp.obj
.PHONY : configurations.obj

# target to build an object file
configurations.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\ORANPacketsSimulator.dir\build.make CMakeFiles/ORANPacketsSimulator.dir/configurations.cpp.obj
.PHONY : configurations.cpp.obj

configurations.i: configurations.cpp.i
.PHONY : configurations.i

# target to preprocess a source file
configurations.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\ORANPacketsSimulator.dir\build.make CMakeFiles/ORANPacketsSimulator.dir/configurations.cpp.i
.PHONY : configurations.cpp.i

configurations.s: configurations.cpp.s
.PHONY : configurations.s

# target to generate assembly for a file
configurations.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\ORANPacketsSimulator.dir\build.make CMakeFiles/ORANPacketsSimulator.dir/configurations.cpp.s
.PHONY : configurations.cpp.s

main.obj: main.cpp.obj
.PHONY : main.obj

# target to build an object file
main.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\ORANPacketsSimulator.dir\build.make CMakeFiles/ORANPacketsSimulator.dir/main.cpp.obj
.PHONY : main.cpp.obj

main.i: main.cpp.i
.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\ORANPacketsSimulator.dir\build.make CMakeFiles/ORANPacketsSimulator.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s
.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\ORANPacketsSimulator.dir\build.make CMakeFiles/ORANPacketsSimulator.dir/main.cpp.s
.PHONY : main.cpp.s

# Help Target
help:
	@echo The following are some of the valid targets for this Makefile:
	@echo ... all (the default if no target is provided)
	@echo ... clean
	@echo ... depend
	@echo ... edit_cache
	@echo ... rebuild_cache
	@echo ... ORANPacketsSimulator
	@echo ... ECPRI.obj
	@echo ... ECPRI.i
	@echo ... ECPRI.s
	@echo ... ORAN.obj
	@echo ... ORAN.i
	@echo ... ORAN.s
	@echo ... Packet.obj
	@echo ... Packet.i
	@echo ... Packet.s
	@echo ... Program.obj
	@echo ... Program.i
	@echo ... Program.s
	@echo ... configurations.obj
	@echo ... configurations.i
	@echo ... configurations.s
	@echo ... main.obj
	@echo ... main.i
	@echo ... main.s
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles\Makefile.cmake 0
.PHONY : cmake_check_build_system

